reduce package size

diff --git a/net.mkiol.SpeechNote.Addon.nvidia.yaml b/net.mkiol.SpeechNote.Addon.nvidia.yaml
--- a/net.mkiol.SpeechNote.Addon.nvidia.yaml
+++ b/net.mkiol.SpeechNote.Addon.nvidia.yaml
@@ -7,6 +7,7 @@ build-options:
   no-debuginfo: true
   prefix: /app/extensions/nvidia
 cleanup:
+  - /bin
   - /include
   - "*.a"
 modules:
@@ -20,6 +21,12 @@ modules:
       - rm -rf builds/bin builds/cuda_sanitizer_api builds/integration
       - rm -rf builds/nsight_compute builds/nsight_systems builds/cuda_gdb builds/cuda_documentation
       - mkdir -p ${FLATPAK_DEST}/cuda
+      - |
+        set -e
+        for f in $(find . -name "*.a" | grep -v "libcudart_static.a" | grep -P "static\.a|static_nocallback"); do
+          echo "removing $f"
+          rm -f "$f"
+        done
       - |
         set -e
         cd builds
@@ -38,11 +45,13 @@ modules:
           echo "copying $f => ${FLATPAK_DEST}/cuda/lib64/"
           cp -P $f ${FLATPAK_DEST}/cuda/lib64/
         done
+      - rm -rf builds
+      - rm -rf cuda_12.9.0_575.51.03_linux.run
+      - ${FLATPAK_DEST}/cuda/bin/nvcc nvcc -arch-ls -code-ls
     build-options:
       strip: true
     cleanup:
       - /cuda/bin
-      - /cuda/extras
       - /cuda/extras
       - /cuda/gds*
       - /cuda/include
@@ -74,11 +83,17 @@ modules:
     only-arches:
       - x86_64
     buildsystem: cmake-ninja
+    build-options:
+      env:
+        NVCC_APPEND_FLAGS: --compress-mode=size --split-compile=0 -Wno-deprecated-gpu-targets
+    cleanup:
+      - /lib/cmake
+      - /lib/pkgconfig
     config-opts:
       - -DCMAKE_BUILD_TYPE=Release
       - -DGGML_NATIVE=OFF
       - -DGGML_CUDA=ON
-      - -DCMAKE_CUDA_ARCHITECTURES=50;52;53;60;61;62;70;72;75;80;86;87;89;90;90a;100;100a
+      - -DCMAKE_CUDA_ARCHITECTURES=50;52;53;60;61;62;70;72;75;80;86;87;89;90;100
       - -DCUDAToolkit_ROOT=/app/extensions/nvidia/cuda
       - -DCMAKE_CUDA_COMPILER=/app/extensions/nvidia/cuda/bin/nvcc
       - -DGGML_AVX=ON
@@ -91,6 +106,8 @@ modules:
       - -DCMAKE_C_FLAGS=-O3
       - -DCMAKE_CXX_FLAGS=-O3
       - -DWHISPER_TARGET_NAME=whisper-cublas
+    post-install:
+      - rm ${FLATPAK_DEST}/lib/libggml.a
     sources:
       - type: archive
         url: https://github.com/ggerganov/whisper.cpp/archive/refs/tags/v1.7.1.tar.gz
@@ -110,6 +127,12 @@ modules:
       - /cuda/include
     build-commands:
       - mkdir -p ${FLATPAK_DEST}/cuda/include
+      - |
+        set -e
+        for f in $(find . -name "*.a"); do
+          echo "removing $f"
+          rm -f "$f"
+        done
       - |
         set -e
         cd include
@@ -134,6 +157,8 @@ modules:
     only-arches:
       - x86_64
     buildsystem: simple
+    build-options:
+      strip: true
     build-commands:
       - |
         set -e
@@ -141,9 +166,8 @@ modules:
         for f in *.so*; do
           echo "copying $f => ${FLATPAK_DEST}/cuda/lib64/"
           cp -P $f ${FLATPAK_DEST}/cuda/lib64/
+          rm -rf $f
         done
-    build-options:
-      strip: true
     sources:
       - type: archive
         archive-type: "tar-zst"
@@ -154,10 +178,19 @@ modules:
     only-arches:
       - x86_64
     buildsystem: simple
+    build-options:
+      strip: true
     cleanup:
       - /oneapi
     build-commands:
       - sh l_BaseKit_p_2024.0.0.49564_offline.sh --extract-folder ./oneapi -a --eula accept --silent --install-dir ${FLATPAK_DEST}/oneapi
+      - chmod -R +w ${FLATPAK_DEST}/oneapi && echo "done" || echo "done with errors"
+      - |
+        set -e
+        for f in $(find ${FLATPAK_DEST}/oneapi -type f -name "*.so*"); do
+          echo "removing $f"
+          rm -f "$f"
+        done
     sources:
       - type: file
         url: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/20f4e6a1-6b0b-4752-b8c1-e5eacba10e01/l_BaseKit_p_2024.0.0.49564_offline.sh
@@ -167,6 +200,8 @@ modules:
     only-arches:
       - x86_64
     buildsystem: cmake-ninja
+    build-options:
+      strip: true
     cleanup:
       - /bin
       - /include
@@ -208,6 +243,7 @@ modules:
       env:
         PYTHONPATH: /app/extensions/nvidia/lib/python3.12/site-packages:/app/lib/python3.12/site-packages
         CTRANSLATE2_ROOT: /app/extensions/nvidia
+        NVCC_APPEND_FLAGS: --compress-mode=size --split-compile=0 -Wno-deprecated-gpu-targets
     cleanup:
       - /bin
       - /include
@@ -253,7 +289,14 @@ modules:
         PYTHONPATH: /app/extensions/nvidia/lib/python3.12/site-packages:/app/lib/python3.12/site-packages
     build-commands:
       - pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}"
-        --prefix=${FLATPAK_DEST} torch torchaudio triton --no-build-isolation
+        --prefix=${FLATPAK_DEST} torch torchaudio triton flash-attn --no-build-isolation
+    post-install:
+      - |
+        set -e
+        for f in $(find ${FLATPAK_DEST}/lib/python3.12/site-packages -maxdepth 1 -name "nvidia*"); do
+          echo "removing $f"
+          rm -rf "$f"
+        done
     sources:
       - type: file
         url: https://files.pythonhosted.org/packages/8b/5c/36c114d120bfe10f9323ed35061bc5878cc74f3f594003854b0ea298942f/torch-2.5.1-cp312-cp312-manylinux1_x86_64.whl
@@ -300,19 +343,6 @@ modules:
       - type: file
         url: https://files.pythonhosted.org/packages/87/20/199b8713428322a2f22b722c62b8cc278cc53dffa9705d744484b5035ee9/nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl
         sha256: 781e950d9b9f60d8241ccea575b32f5105a5baf4c2351cab5256a24869f12a1a
-
-  - name: python3-flash-attn-cuda
-    only-arches:
-      - x86_64
-    buildsystem: simple
-    build-options:
-      strip: true
-      env:
-        PYTHONPATH: /app/extensions/nvidia/lib/python3.12/site-packages:/app/lib/python3.12/site-packages
-    build-commands:
-      - pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}"
-        --prefix=${FLATPAK_DEST} flash-attn --no-build-isolation
-    sources:
       - type: file
         url: https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.4.post1/flash_attn-2.7.4.post1+cu12torch2.5cxx11abiFALSE-cp312-cp312-linux_x86_64.whl
         dest-filename: flash_attn-2.7.4.post1-cp312-cp312-linux_x86_64.whl
